Perform the following operations using Python on any open source dataset (e.g., data.csv)
1.	Import all the required Python Libraries.
2.	Locate an open source data from the web (e.g., https://www.kaggle.com). Provide a clear              description of the data and its source (i.e., URL of the web site).
3.	Load the Dataset into pandas dataframe.
4.	Data Preprocessing: check for missing values in the data using pandas isnull(), describe() function to get some initial statistics. Provide variable descriptions. Types of variables etc. Check the dimensions of the data frame.
5.	Data Formatting and Data Normalization: Summarize the types of variables by checking the data types (i.e., character, numeric, integer, factor, and logical) of the variables in the data set. If variables are not in the correct data type, apply proper type conversions.
6.	Turn categorical variables into quantitative variables in Python.

In addition to the codes and outputs, explain every operation that you do in the above steps and explain everything that you do to import/read/scrape the data set.

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/sample_data/california_housing_test.csv")

In [3]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [4]:
df.isnull()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
2995,False,False,False,False,False,False,False,False,False
2996,False,False,False,False,False,False,False,False,False
2997,False,False,False,False,False,False,False,False,False
2998,False,False,False,False,False,False,False,False,False
2999,False,False,False,False,False,False,False,False,False

In [6]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [7]:
df.shape

(3000, 9)

In [8]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

In [9]:
df.notnull().sum()

longitude             3000
latitude              3000
housing_median_age    3000
total_rooms           3000
total_bedrooms        3000
population            3000
households            3000
median_income         3000
median_house_value    3000
dtype: int64

In [11]:
df.ndim

2

In [12]:
df.size

27000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

In [14]:
df["latitude"]=df["latitude"].astype(int)

In [15]:
df.dropna()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [18]:
df["latitude"]=df["latitude"].astype(int)

In [19]:
df["latitude"].replace({"37":0},inplace=true)

NameError: name 'true' is not defined

In [16]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0